import { describe, expect, test } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadWorldManifest, saveWorldManifest, validateReferences, projectToThree, projectToGodot, checkGodotExportPreflight, WorldManifestError, type GodotToolchainProbe } from "../../src/worldmanifest/manifest";
import { loadStudioConfig, StudioConfigSchema } from "../../src/config";
import { createGodotObservabilitySurface, godotObservabilityUnavailable } from "../../../adapters/src/godot/observability";

function tmpProject(): string {
  return mkdtempSync(join(tmpdir(), "gauntlet-godot-"));
}

function writeManifest(root: string, overrides: Record<string, unknown> = {}): string {
  const manifest = {
    schema: "gauntlet.world.manifest",
    schema_version: "1.0",
    id: "relay-island",
    game_id: "blackwater-relay",
    zones: [
      { id: "beach", name: "Landing Beach", bounds: { min: [-50, 0, -50], max: [50, 12, 50] } },
      { id: "relay-station", name: "Relay Station" },
    ],
    placements: [
      {
        id: "radio-mast",
        zone: "relay-station",
        asset_ref: "reservoir:radio-mast",
        position: [0, 0, 0],
        rotation_euler: [0, 1.57, 0],
        sockets: { antenna_mount: [0, 4.2, 0] },
      },
    ],
    scatter_rules: [
      { id: "palm-scatter", zone: "beach", asset_ref: "reservoir:palm", density_per_100m2: 4, seed: 7 },
    ],
    lighting: { summary: "overcast late afternoon", params: { sun_elevation: 22, exposure: 0.85 } },
    atmosphere: { summary: "sea haze", params: { fog_density: 0.02 } },
    colliders: [{ id: "radio-mast-collider", placement_ref: "radio-mast", kind: "capsule" as const, params: { radius: 0.4, height: 8 } }],
    navigation: { surfaces: ["beach", "relay-station"], agent_radius: 0.5, summary: "referenced, generated by navigation capability" },
    terrain_ref: "canonical-terrain-heightfield",
    spawn_points: [{ id: "player-spawn", zone: "beach", position: [0, 1, 40], kind: "player" as const }],
    interaction_anchors: [{ id: "mast-interact", placement_ref: "radio-mast", interaction: "repair relay" }],
    lod_policy: { per_asset: { "reservoir:radio-mast": "3 levels" } },
    streaming_hints: [{ zone: "relay-station", policy: "always-loaded" }],
    built_from: 1,
    reads: ["worlds"],
    ...overrides,
  };
  const dir = join(root, ".studio", "worlds");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "relay-island.json");
  writeFileSync(path, JSON.stringify(manifest));
  return path;
}

describe("world manifest validation and references", () => {
  test("valid manifest loads; broken references are reported", () => {
    const root = tmpProject();
    const path = writeManifest(root);
    const manifest = loadWorldManifest(path);
    expect(validateReferences(manifest)).toEqual([]);

    const broken = loadWorldManifest(path);
    (broken as { placements: { zone: string }[] }).placements[0].zone = "nowhere";
    // validateReferences is pure: operate on the mutated copy directly.
    const problems = validateReferences({ ...broken });
    expect(problems.some((p) => p.includes("unknown zone 'nowhere'"))).toBe(true);
    rmSync(root, { recursive: true, force: true });
  });

  test("invalid manifests are typed-rejected", () => {
    const root = tmpProject();
    const path = writeManifest(root, { schema: "gauntlet.world.manifest.v9" });
    expect(() => loadWorldManifest(path)).toThrow(WorldManifestError);
    expect(() => loadWorldManifest(join(root, "missing.json"))).toThrow(/NOT_FOUND/);
    rmSync(root, { recursive: true, force: true });
  });
});

describe("TEETH-T32-001: deterministic projections; scene state is never authority", () => {
  test("three projection is byte-identical across regenerations", () => {
    const root = tmpProject();
    const manifest = loadWorldManifest(writeManifest(root));
    const a = JSON.stringify(projectToThree(manifest));
    const b = JSON.stringify(projectToThree(loadWorldManifest(writeManifest(root))));
    expect(a).toEqual(b);
    expect(a).toContain("gauntlet-three");
    rmSync(root, { recursive: true, force: true });
  });

  test("godot projection regenerates byte-identically and consumes the same manifest", () => {
    const root = tmpProject();
    const manifest = loadWorldManifest(writeManifest(root));
    const a = projectToGodot(manifest);
    const b = projectToGodot(loadWorldManifest(writeManifest(root)));
    expect(JSON.stringify(a)).toEqual(JSON.stringify(b));
    const files = Object.fromEntries(a.files.map((f) => [f.path, f.content]));
    expect(files["project.godot"]).toContain("config_version=5");
    expect(files["scripts/world_builder.gd"]).toContain("MANIFEST :=");
    expect(files["world_manifest.json"]).toEqual(JSON.stringify(manifest, null, 2));
    expect(files["export_presets.cfg"]).toContain("godot.web");
    expect(files["export_presets.cfg"]).toContain("godot.ios");
    rmSync(root, { recursive: true, force: true });
  });

  test("manifest references stay references: terrain and navigation are never embedded as data", () => {
    const root = tmpProject();
    const manifest = loadWorldManifest(writeManifest(root));
    const three = projectToThree(manifest);
    expect(three.terrain_ref).toBe("canonical-terrain-heightfield");
    expect(three.navigation.surfaces).toEqual(["beach", "relay-station"]);
    expect((three as unknown as Record<string, unknown>).heightfield).toBeUndefined();
    rmSync(root, { recursive: true, force: true });
  });
});

describe("TEETH-T32-002: godot-absent export is typed blocked", () => {
  const unavailableProbe: GodotToolchainProbe = {
    godotVersion: () => null,
    platform: () => "linux",
  };
  const availableProbe: GodotToolchainProbe = {
    godotVersion: () => "4.3.stable",
    platform: () => "linux",
  };

  test("godot binary absent → typed blocked, requirements named, no readiness claimed", () => {
    for (const target of ["godot.web", "godot.android", "godot.ios"] as const) {
      const preflight = checkGodotExportPreflight(target, unavailableProbe);
      expect(preflight.status).toBe("blocked");
      expect(preflight.code).toBe("TOOLCHAIN_UNAVAILABLE");
      expect(preflight.requirements.length).toBeGreaterThan(0);
    }
  });

  test("iOS on a non-macOS host is typed blocked even with godot present", () => {
    const preflight = checkGodotExportPreflight("godot.ios", availableProbe);
    expect(preflight.status).toBe("blocked");
    expect(preflight.detail).toContain("macOS");
  });

  test("web target with godot present is available (no readiness forgery)", () => {
    const preflight = checkGodotExportPreflight("godot.web", availableProbe);
    expect(preflight.status).toBe("available");
  });
});

describe("TEETH-T32-003: production mutation lockout on the Godot observability surface", () => {
  function fakeBridge() {
    return {
      ready: () => true,
      readiness: () => ({ renderer: true, physics: true }),
      tick: () => 42,
      entities: () => ({
        list: () => [{ id: "e1" }],
        get: (id: string) => ({ id }),
        snapshot: () => ({ entities: [] }),
      }),
      errors: () => ({ recent: () => [] }),
      renderer: () => ({ probe: () => ({}), stats: () => ({}), capture: () => null }),
      physics: () => ({ read: () => ({}) }),
      navigation: () => ({ read: () => ({}) }),
      spatial: () => ({ read: () => ({}) }),
      network: () => ({ read: () => ({}) }),
      views: () => ({ list: () => [], get: (_id: string) => null, current: () => null }),
    };
  }

  test("valid bridge wraps into the versioned contract in development mode", () => {
    const result = createGodotObservabilitySurface(fakeBridge(), { mode: "development" });
    expect(result.ok).toBe(true);
    expect(result.surface).toBeDefined();
  });

  test("production lockout: a bridge smuggling privileged mutation APIs fails inspection", () => {
    const hostile = fakeBridge() as Record<string, unknown>;
    hostile["control"] = { pause: () => {}, step: (_n: number) => {} };
    const result = createGodotObservabilitySurface(hostile as never, { mode: "production" });
    expect(result.ok).toBe(false);
    expect(result.productionViolations.length).toBeGreaterThan(0);
  });

  test("absent bridge is honest typed blockage, never fabricated reads", () => {
    const blocked = godotObservabilityUnavailable("native target has no debug bridge attached");
    expect(blocked.code).toBe("GODOT_OBSERVABILITY_BRIDGE_UNAVAILABLE");
    expect(blocked.surface).toBeUndefined();
  });
});

describe("TEETH-T32-004: production targets are additive; existing configs untouched", () => {
  test("config without production block still validates (reference runtime unchanged)", () => {
    const schema = StudioConfigSchema.safeParse({ project_id: "p", title: "t" });
    expect(schema.success).toBe(true);
    const parsed = StudioConfigSchema.parse({ project_id: "p", title: "t" });
    expect(parsed.runtime.engine).toBe("three");
    expect(parsed.production).toBeUndefined();
  });

  test("config with production targets validates and keeps engine three", () => {
    const parsed = StudioConfigSchema.parse({
      project_id: "p",
      title: "t",
      production: { targets: [{ id: "godot.web" }, { id: "godot.android", quality_profile: "android-mid" }] },
    });
    expect(parsed.runtime.engine).toBe("three");
    expect(parsed.production?.targets.length).toBe(2);
  });

  test("invalid target id is rejected", () => {
    const result = StudioConfigSchema.safeParse({
      project_id: "p",
      title: "t",
      production: { targets: [{ id: "unity.web" }] },
    });
    expect(result.success).toBe(false);
  });

  test("existing game configs keep loading through loadStudioConfig", () => {
    const config = loadStudioConfig(join(REPO_ROOT, "examples", "blackwater-relay"));
    expect(config.runtime.engine).toBe("three");
  });
});

const REPO_ROOT = join(import.meta.dir, "..", "..", "..", "..");
