import type { CapabilityDescriptor } from "@gauntlet/contracts";

/**
 * Normative Studio Capability Catalog.
 * Defines the stable studio capabilities independently of specific provider implementations.
 */
export const CAPABILITY_CATALOG: CapabilityDescriptor[] = [
  {
    id: "world.composition",
    summary: "Scene and world composition, architecture, vegetation, lighting, atmosphere, and environment construction via 3dviz. Composes environments from approved assets and procedural placement.",
    use_when: [
      "scene composition",
      "environment design",
      "lighting setup",
      "atmosphere",
      "world layout",
      "architecture",
      "vegetation placement",
    ],
    do_not_use_when: [
      "reconstructing a single depicted object or character from reference image",
      "procedural terrain heightfield calculation",
      "navmesh generation",
    ],
    inputs: ["world_brief", "environment_theme", "layout_spec"],
    outputs: ["scene_graph_spec", "world_manifest"],
    verification: ["visual_capture", "draw_call_telemetry"],
    providers: ["agent-skill.3dviz"],
  },
  {
    id: "asset.reconstruct",
    summary: "Reconstruct a specific depicted object or character into procedural Three.js from suitable reference imagery. Produces high-fidelity object geometry honoring reference silhouette and budgets.",
    use_when: [
      "reconstructing a depicted object from reference image",
      "character model from reference photo",
      "field transceiver from concept art",
      "specific vehicle from drawing",
    ],
    do_not_use_when: [
      "generic text-to-3D without reference image",
      "scene composition",
      "world environment layout",
      "procedural terrain",
    ],
    inputs: ["reference_image_uri", "target_role", "poly_budget"],
    outputs: ["procedural_three_code", "glb_derivative"],
    verification: ["reference_similarity", "poly_budget_check"],
    providers: ["agent-skill.img2threejs"],
    requires_user_reference: true,
  },
  {
    id: "world.terrain",
    summary: "Deterministic mathematical procedural elevation generation producing canonical TerrainHeightfield height arrays. Generates multi-octave island topography with deterministic seed control.",
    use_when: [
      "procedural terrain generation",
      "heightfield elevation",
      "island topography",
      "elevation grid",
    ],
    do_not_use_when: [
      "importing static pre-modeled scenic meshes",
      "environment composition",
      "reconstructing objects",
    ],
    inputs: ["seed", "grid_dimensions", "world_bounds", "octaves"],
    outputs: ["TerrainHeightfield"],
    verification: ["height_range_check", "deterministic_seed_check"],
    providers: ["procedural_generator"],
  },
  {
    id: "world.physics",
    summary: "Direct Rapier 3D simulation step owner; creates colliders and dynamic bodies as execution projections. Manages physical simulation stepping without leaking authority into gameplay state.",
    use_when: [
      "rigid body physics",
      "collision detection",
      "character controller physics",
      "raycast queries against physics world",
    ],
    do_not_use_when: [
      "authoritative gameplay state",
      "pure visual animations",
    ],
    inputs: ["physics_world_config", "colliders_spec"],
    outputs: ["physics_step_owner"],
    verification: ["collision_event_log", "step_timing_telemetry"],
    providers: ["physics.rapier"],
  },
  {
    id: "world.navigation",
    summary: "Recast navmesh generation, crowd simulation, and deterministic pathfinding over accepted world geometry. Calculates collision-aware routes and agent steering for ground entities.",
    use_when: [
      "AI pathfinding",
      "navmesh generation",
      "crowd navigation",
      "patrol route planning",
    ],
    do_not_use_when: [
      "free-flight aerial navigation",
      "direct player movement without collision",
    ],
    inputs: ["world_geometry_source", "agent_radius", "agent_height"],
    outputs: ["navmesh_data", "path_query_handle"],
    verification: ["path_traversal_test"],
    providers: ["navigation.recast"],
  },
  {
    id: "world.spatial",
    summary: "Accelerated Three.js raycasts and spatial bounds queries using three-mesh-bvh. Provides accelerated line-of-sight and spatial acceleration structures for runtime geometry.",
    use_when: [
      "accelerated raycasting",
      "line-of-sight checks",
      "spatial queries against meshes",
    ],
    do_not_use_when: [
      "authoritative game state",
      "physics simulation stepping",
    ],
    inputs: ["target_mesh"],
    outputs: ["bvh_acceleration_structure"],
    verification: ["raycast_benchmark"],
    providers: ["spatial.three-mesh-bvh"],
  },
  {
    id: "asset.source",
    summary: "CC0, HDRI, and licensed PBR material and asset intake with provenance tracking. Ingests textures, environment skyboxes, and model assets with strict licensing verification.",
    use_when: [
      "intake of CC0 textures",
      "HDRI skybox sourcing",
      "licensed PBR assets",
    ],
    do_not_use_when: [
      "generating new AI meshes",
      "reference image reconstruction",
    ],
    inputs: ["source_url", "license_type"],
    outputs: ["AssetRecord", "cached_texture_set"],
    verification: ["license_verification", "checksum_verification"],
    providers: ["asset.polyhaven"],
  },
  {
    id: "asset.optimize",
    summary: "glTF-Transform offline pipeline for mesh pruning, LOD generation, and WebP/KTX2 texture compression. Optimizes production assets to meet target triangle, draw call, and memory budgets.",
    use_when: [
      "glTF optimization",
      "texture compression to WebP",
      "geometry pruning",
      "LOD generation",
    ],
    do_not_use_when: [
      "runtime scene rendering",
      "procedural generation",
    ],
    inputs: ["raw_gltf_path", "compression_profile"],
    outputs: ["optimized_glb_path", "budget_report"],
    verification: ["gltf_validator", "file_size_check"],
    providers: ["asset.gltf-transform"],
  },
  {
    id: "asset.dcc_escalate",
    summary: "Blender DCC escalation for topology cleanup, UV unwrap, complex rigging, and texture baking. Used when procedural generation cannot satisfy difficult topology or skinning constraints.",
    use_when: [
      "topology cleanup",
      "complex character skinning",
      "difficult UV unwrap",
      "texture baking",
    ],
    do_not_use_when: [
      "default game scene authoring",
      "authoritative game state",
    ],
    inputs: ["source_blend_path", "export_script"],
    outputs: ["committed_glb_derivative"],
    verification: ["mesh_manifold_check"],
    providers: ["dcc.blender"],
  },
  {
    id: "vfx.particles",
    summary: "Inspectable particle systems and visual effects using three.quarks. Creates localized particle emitters, smoke, sparks, and glow effects as execution projections over the scene graph.",
    use_when: [
      "beacon glow",
      "spark effects",
      "engine exhaust",
      "smoke and dust particles",
    ],
    do_not_use_when: [
      "solid world geometry",
      "gameplay collision colliders",
    ],
    inputs: ["particle_emitter_config"],
    outputs: ["quarks_system"],
    verification: ["particle_count_budget"],
    providers: ["vfx.quarks"],
  },
  {
    id: "audio.procedural",
    summary: "Browser procedural and sample audio backend implementing AudioBackend via Tone.js with NullAudioBackend in headless environments. Drives spatial audio effects and procedural engine sounds.",
    use_when: [
      "engine sound",
      "ambient island wind",
      "beacon activation audio",
      "UI sound effects",
    ],
    do_not_use_when: [
      "visual rendering",
      "gameplay state authority",
    ],
    inputs: ["audio_event_spec"],
    outputs: ["audio_handle"],
    verification: ["gesture_unlock_test", "headless_silence_test"],
    providers: ["audio.tone", "audio.null"],
  },
  {
    id: "network.multiplayer",
    summary: "Multiplayer replication and transport with Bun WebSockets baseline and optional WebRTC datagrams. Provides authoritative server tick synchronization and entity state replication.",
    use_when: [
      "multiplayer client-server synchronization",
      "authoritative server tick",
      "state replication",
    ],
    do_not_use_when: [
      "single-player local state",
      "offline tests",
    ],
    inputs: ["transport_config", "entity_replication_schema"],
    outputs: ["network_session_handle"],
    verification: ["packet_loss_simulation", "reconciliation_test"],
    providers: ["network.websocket", "network.geckos"],
  },
  {
    id: "verify.browser",
    summary: "Deterministic browser proof scenarios and telemetry capture using Playwright, with agent-browser for exploratory inspection. Captures authoritative state, pixels, and performance telemetry.",
    use_when: [
      "deterministic browser end-to-end proof",
      "pixel capture verification",
      "scenario regression",
    ],
    do_not_use_when: [
      "exploratory browser debugging without assertions",
    ],
    inputs: ["scenario_spec", "target_url"],
    outputs: ["ObservationRun", "EvidenceManifest"],
    verification: ["playwright_trace_validation"],
    providers: ["browser.playwright", "browser.agent-browser"],
  },
  {
    id: "world.environment.compose",
    summary:
      "Agent-skill world/environment composition handoff (3dviz-pro-max): composes architecture, vegetation, lighting, and atmosphere as world kits, sockets, colliders, and scatter metadata integrating with canonical terrain and runtime navigation. Verification is deterministic; composition never owns terrain elevation, navmesh, or specific-object reconstruction.",
    use_when: [
      "scene/world composition",
      "environment construction",
      "architecture placement",
      "vegetation scatter",
      "lighting and atmosphere",
    ],
    do_not_use_when: [
      "reconstructing a specific depicted object or character from reference imagery",
      "terrain elevation authority or heightfield generation",
      "navigation authority or navmesh data production",
    ],
    inputs: ["world_brief", "terrain_heightfield_ref", "kit_asset_ids"],
    outputs: [
      "world_kit_placements",
      "socket_bindings",
      "collider_specs",
      "scatter_metadata",
      "lighting_atmosphere_spec",
    ],
    verification: [
      "deterministic_result_verification",
      "authority_boundary_check",
      "asset_provenance_reference_check",
    ],
    providers: ["agent-skill.3dviz"],
  },
  {
    id: "asset.reconstruct.reference-image",
    summary: "Reference-image reconstruction of one specific depicted object or character into a procedural Three.js module via the pinned img2threejs agent skill. Requires suitable authorized reference imagery before routing; the accepted handoff output is verified deterministically (imports, provenance, reference evidence, affordances, budgets) against the single standard Three.js dependency.",
    use_when: [
      "reconstructing a specific depicted object with suitable reference imagery",
      "reconstructing a specific depicted character from reference photo or concept art",
      "reference-backed prop or vehicle reconstruction with authorized image",
    ],
    do_not_use_when: [
      "generic text-to-3D generation without a suitable reference image",
      "scene composition or world environment layout",
      "procedural terrain heightfield generation",
      "navmesh generation",
    ],
    inputs: ["reference_image_uris", "target_role", "budget_limits", "min_reference_similarity"],
    outputs: ["procedural_three_module", "asset_record", "verification_evidence"],
    verification: ["deterministic_result_verification", "reference_comparison_evidence", "budget_check"],
    providers: ["agent-skill.img2threejs"],
    requires_user_reference: true,
    cost_class: "metered",
  },
];
